### ISSUE TITLE
incompatible with Monterey developer preview 5

### ISSUE THREAD

**Issue by dtoub** [apparition47/MailTrackerBlocker#132]
Monterey developer preview 5 disables MailTrackerBlocker entirely. Any word on an update?

**Comment by apparition47** [comment]
No plans to support Monterey since it already includes a similar feature. My suggestion at this time is to [enable that built-in **Mail Privacy Protection**](https://www.howtoisolve.com/how-to-enable-mail-privacy-protection-on-macos-iphone/) and [uninstall MailTrackerBlocker](https://github.com/apparition47/MailTrackerBlocker#to-uninstall).
