### ISSUE TITLE
Can't install it through brew…

### ISSUE THREAD

**Issue by applebait** [apparition47/MailTrackerBlocker#136]
Today I decided to delete everything related to mailtrackerblocker, just because I was having it duplicated whenever I ran brew upgrade.
Now I'm trying to install it again but Brew reports there's no mailtrackerblocker formulae, nor Cask…
Do I need to clone it from Git?
TiA

**Comment by apparition47** [comment]
That's odd. It's listed on the [brew directory](https://formulae.brew.sh/cask/mailtrackerblocker).

If you used brew for MailTrackerBlocker in the past, you may have used my tap. I'm still maintaining it but it's safe to remove it in favour of the official tap:  `brew untap apparition47`.

And no need to git clone. Trying `brew update` should update your local formulae/cask cache. Otherwise you might need to check on Homebrew's repo for answers: https://github.com/Homebrew/homebrew-core/issues/37724

**Comment by applebait** [comment]
No luck…
Already ran:
_sudo rm -rf `brew --cache`_
and then both for cask and formulae with this results:
_❯ brew install --cask mailtrackerblocker
Error: Cask 'mailtrackerblocker' is unavailable: No Cask with this name exists.
❯ brew install mailtrackerblocker
Warning: No available formula or cask with the name "mailtrackerblocker". Did you mean mailcatcher?
==> Searching for similarly named formulae...
This similarly named formula was found:
mailcatcher
To install it, run:
  brew install mailcatcher
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps._

**Comment by apparition47** [comment]
Happy to hear that!
