### ISSUE TITLE
Monterey: Mail doesn't show MailTrackerBlocker as installed

### ISSUE THREAD

**Issue by octothorpe8** [apparition47/MailTrackerBlocker#160]
In the Extensions section of Mail's preferences, MailTrackerBlocker does not show up and it looks as if no extensions are installed. But when I open an email, I can see the blue "✕" symbol that indicates the plugin is functioning.

**Comment by apparition47** [comment]
That's because MailTrackerBlocker isn't a `Mail Extension` (introduced in Monterey); it's a mailbundle/mail plugin (access from: Preferences > General > Manage Plug-ins...).

Apple mentioned that mail plugins will stop working in some future release of macOS (maybe macOS 13?). I'm not really sure if there's enough interest in having MailTrackerBlocker rewritten into a Mail Extension since Mail Privacy Protection is a thing.
